config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get "resume"     => 'resume#show'
  get "backend"    => 'static_pages#backend'
  get 'learn_html' => 'learn#html'
  get 'learn_css'  => 'learn#css'
  get 'learn_javascript' => 'learn#javascript'
  get 'learn_rails' => 'learn#rails'
  get 'userpanel'  =>  'users#panel'
  get 'about'      =>  'static_pages#about'
  get 'contact'    =>  'static_pages#contact'
  
  
  get "signup"     => 'users#new'
  get "login"      => 'sessions#new'
  get "adminpanel" => 'articles#new'
  
  
  post "adminpanel" => 'articles#new_link'
  post "login"      => 'sessions#create'
  post "/"          => 'static_pages#create'
  post 'contact'=> 'static_pages#new_contact'
  resources :articles, :except => [:new] do
    member do 
      post 'like'
      post 'comment'
    end
  end
  resources :users
  resources :quotes
  resources :forums
  resources :videos, :except => [:new] do
    member do
      post 'like'
      post 'comment'
    end
  end  
  
  
  
  delete 'logout' => 'sessions#destroy'
  delete 'videos/:id' => 'videos#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def about
    end
    
    def contact
    end
    
    def new_contact
        @contact_us = ContactU.new(contact_us_params)
        if @contact_us.save
           flash[:success] = "Successfully Submitted!"
           redirect_to '/contact'
        end
    end
    
    def home
        @articles = Article.all.sort_by{| likes | likes.thumbs_up_total}.reverse
        @videos = Video.all.sort_by{| likes | likes.thumbs_up_total}.reverse
        @quotes = Qoute.all.sort
        begin
            @daily_quote = Qoute.process_quote(@quotes)
        rescue Exception => e  
            puts e.message  
        end
    end
    
    def backend
        @articles = Article.all
        @videos = Video.all
    end
    
    def create 
       @subscription = Subscription.new(subs_params) 
       if @subscription.save
           flash[:success] = "Successfully Subscribed!"
           redirect_to '/'
       end
    end
    
    private
        def subs_params
           params.require(:subscription).permit(:name, :email)
        end
        
        def contact_us_params
           params.require(:contact_us).permit(:email, :phone, :name, :message)
        end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def amounts
       ["$2", "$5", "$10", "$15", "$20", "$30", "$50"] 
    end
end

app/views/static_pages/about.html.erb
<div class="container">
    <h3>Our Story</h3>
    <hr>
    <p>This website was created as part of my web development learning process, 
    also with intention to better myself at writing articles however in the 
    process I decided to make it to help other people who want to become web 
    developers also and guide them through the process, give advise and motivation 
    from my own learning experience.
    </p>
    
    <p>
        My journey in to programming started around 2010 after coming across a 
        video lectures on youtube from Stanford University called "Programming
        Methodology in java 
        (<a href="https://www.youtube.com/watch?v=KkMDCCdjyW8&list=PLB727981776561EB5&index=1">here</a>)"
        . I was blown away by the proffessor Mehran Sahami and after finishing 
        those lectures I thought to mysel - wow finally I found something that I
        am really interested in. Its been a bumpy journey since then learning Java 
        on and off but in October 2015, after getting a job as a Support Engineer
        in a Cloud Software company I have fully resumed my studies in to programming
        and dove deep in to Web Development, more specifically using Ruby on Rails
        framework. I can not say that this past period was easy also due to the 
        time limitations and personal life events. I will make a video soon
        telling my full learning story and obsticles I had to overcome. Keep in 
        mind that I still considering myself a fresh Web Developer and surely not an
        expert by any means but hoepfully we can engage in this journey together and
        share the good and the bad. <br><br>
        
        Cheers!<br>
        
        Julius
    </p>
</div>

app/views/static_pages/backend.html.erb
<% provide(:title, 'Home') %>
<!-- Header daily quote -->
<div class="container" id="white-line-be">
    <div class="row">
        <div id="header-title">
            <b id="daily_quote_title-be">Daily Quote:</b>
            <p id="daily_quote-be" class="center">“I can accept failure. 
               Everyone fails at something. But I can’t accept not trying.”</p>
            <b id="signature">-Michael Jordan</b>
        </div>
    </div>    
</div>
<!-- switch between front end and backend -->
<div class="jumbotron">
    <h4>Everything About (Railsy) Web Development.</h4> 
    <div class="btn-group">
    <%= link_to "Front End", root_path, class: "btn btn-sm btn-default sharp" %>
    <%= link_to "Back End"  , backend_path, class: "btn btn-sm btn-danger sharp" %>
    </div>
</div>

<!-- Welcome video -->
<div class="container">
    <div class="row">
        <div id="header-title-be">
            <iframe width="100%" height="700"
                src=<%= "https://www.youtube.com/embed/0NjkfHbK6BE" %> frameborder="0" allowfullscreen>
            </iframe>
        </div>
    </div>    
</div>

<div class="container">
    <div class="row">
        <h1>Articles</h1>
    </div>    
</div>

<!-- iteration count variable -->
    <% break_int   = 0 %>
    <% break_video = 0 %>
<!-- Display Articles -->
<div class="container">
    <div class="row">
        <%= @articles.find_each do |x| %>
            <div class="col col-sm-4 col-md nopadding">
                <div id="image-be" class="center">
                    <% if x.picture? %>
                        <%= link_to image_tag(x.picture.url, size: "400x300", class: "gravatar"),
                                              article_path(x.id)  %>
                    <% else %>
                        <%= link_to image_tag("ruby.png", size: "400x300", class: "gravatar"),
                                          article_path(x.id)  %>
                    <% end %>                      
                        <h4><%= link_to x.title, article_path(x.id), id: "title_p-be" %></h4>
                        <!--<%= truncate(x.text, :length => 145) %> -->
                </div>
            </div> 
            <!-- break out of block when article count reaches 6 -->
            <% break_int += 1 %>
            <% break if break_int == 6 %>
        <% end %>
        <div class="center">
            <%= link_to "Show More Articles", articles_path, class: "btn btn-md btn-default" %>
        </div>
    </div>
</div>
<!-- Display videos -->
<div class="container"> 
    <div class="row">
        <h1>Videos</h1>
        <%= @videos.find_each do |x| %>
            <div class="col col-sm-4 col-md">
                <div id="video-be" class="center">
                    <% puts "#{x.link}" %>
                    <iframe width="380" height="300" id="video"
                        src=<%= "https://www.youtube.com/embed/#{x.link}" %> frameborder="0" allowfullscreen>
                    </iframe>
                    <h4>Stick Your Video Here <!-- add id=""title_p" when you will have embeded ruby --></h4>
                </div>
            </div>
            <% break_video += 1 %>
            <% break if break_video == 6 %>
        <% end %> 
        <div class="center">
            <%= link_to "Show More Videos", videos_path, class: "btn btn-md btn-default" %>
        </div>
    </div>
</div>
<!-- subscription form, pure bootstrap -->
<section>
    <div class="well">
        <div class="container text-center">
          <h2>Subscribe</h2>  
          <p style="color: black">Enter Your Name and Email</p>
          <form action="" class="form-inline">
              <div class="form-group">
                  <label for="subscription">Subscribe</label>
                  <input type="text" class="form-control" id="subscription-be" placeholder="Your Name">
              </div>
              <div class="form-group">
                  <label for="email">Email Address</label>
                  <input type="text" class="form-control" id="email-be" placeholder="Email">
              </div>
              <button type="submit" class="btn btn-default">Subscribe</button>
          </form>
        </div>
    </div>
</section>

app/views/static_pages/contact.html.erb
<div class="row center">
    <h4>Contact Us</h4>
    <div class="col-md-6 col-md-offset-3">
        <%= form_for :contact_us do |x| %>
        
            <h4><%= x.label "Name" %></h4>
            <%= x.text_field :name, size: "20x5", class: "form-control" %>
            
            <h4><%= x.label "Email" %></h4>
            <%= x.text_field :email, size: "20x5", class: "form-control" %>
            
            <h4><%= x.label "Phone Number" %></h4>
            <%= x.text_field :phone, size: "20x5", class: "form-control" %>
            
            <h4><%= x.label "Message" %></h4>
            <%= x.text_area :message, size: "20x5", class: "form-control" %>
    
            <%= x.submit "Send", class: "btn btn-md btn-success buttons-width" %>
        
        <% end %>
    </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<!-- Header daily quote -->
<div class="container">
    <div class="row">
            <b id="daily_quote_title">Daily Quote:</b>
            <blockquote id="daily_quote" class="center">“<%=  @daily_quote.quote if !@daily_quote.blank? %>”</blockquote>
            <i id="signature"><i>-<%= @daily_quote.author if !@daily_quote.blank? %></i></i>
    </div>   
</div>
<!-- switch between front end and backend -->
<div class="jumbotron" id="heading">
    <h2 id="jumbotron-text">Become a Web Developer.</h2> 
    <%= link_to "Sign Up Now!", signup_path, class: "btn btn-md btn-default" %>
    <div id="donate-button">
        <p id="donate-p">Donate <a class="btn btn-sm btn-danger button-style" href="https://www.google.com">$</a></p>
    </div>
</div>

<!-- Welcome video -->
<div class="container">
    <div class="row">
        <div>
            <iframe width="100%" height="700"
                src=<%= "https://www.youtube.com/embed/0NjkfHbK6BE" %> frameborder="0" allowfullscreen>
            </iframe>
        </div>
    </div>    
</div>

<div class="container">
    <div class="row">
        <h1>Popular Articles</h1>
    </div>    
</div>
<!-- iteration count variable -->
    <% break_int   = 0 %>
    <% break_video = 0 %>
<!-- Display Articles -->
<div class="container">
    <div class="row center">
        <% @articles.each do |x| %>
            <div class="col-sm-6 col-md-4">
                <div class="image">
                <% if x.picture? %>
                        <%= link_to image_tag(x.picture.url),
                                         article_path(x.id)%>
                <% else %>
                        <%= link_to image_tag("ruby.png"),
                                    article_path(x.id)  %>
                <% end %>
                    <div class="article-title">
                        <h4><%= link_to x.title, article_path(x.id), id: "title_p" %></h4>
                        <div style="color: white">
                            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        <%= x.thumbs_up_total %>  &nbsp
                        <i class="fa fa-comments" aria-hidden="true"></i>
                        <%= x.comments_total %>
                        </div>
                        <!--<%= truncate(x.text, :length => 145) %> -->
                    </div>    
                </div>    
            </div> 
            <!-- break out of block when article count reaches 6 -->
            <% break_int += 1 %>
            <% break if break_int == 6 %>
        <% end %>
        <div class="center">
            <%= link_to "Show More Articles", articles_path, class: "btn btn-md btn-default" %>
        </div>
    </div>
</div>
<!-- Display videos -->
<hr>
<div class="container"> 
    <div class="row">
        <h1>Popular Videos</h1>
        <% @videos.each do |x| %>
            <div class="col-md-3 col-sm-6 center">
                    <iframe src=<%= "https://www.youtube.com/embed/#{x.link}" %>
                                    frameborder="0" allowfullscreen class="video">
                    </iframe>
                    <h4><%= link_to x.title, video_path(x.id) %></h4>
                    <div style="color: white">
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        &nbsp <%= x.thumbs_up_total %> &nbsp
                        <i class="fa fa-comment-o" aria-hidden="true"></i>
                        &nbsp <%= x.comments_total %>
                    </div>
            </div>
            <% break_video += 1 %>
            <% break if break_video == 8 %>
        <% end %> 
        <div class="center">
            <%= link_to "Show More Videos", videos_path, class: "btn btn-md btn-default" %>
        </div>
    </div>
</div>
<!-- subscription form, pure bootstrap -->
<!--<div class="container">-->
<!--<div class="container">
    <%= form_for :subscription do |subs| %>
        <div class="donate-style">       
        <%= subs.label 'Donate', style: "color: white" %>
        <%= subs.select :state, options_for_select(amounts) %>
        <%= subs.text_field :email, id: "donate-style",  placeholder: "$" %>
        <%= subs.submit '$', class: "btn btn-xs btn-success buttons-width" %>
        </div>
    <% end %>
</div>-->
<div id="subscribe">
    <div class="container center">
         <%= react_component('SubscribeMessage', name: 'for the Latest News') %>
         <p class="subscribe_text">Enter Your Name and Email</p>
         <%= form_for :subscription do |subs| %>

            <%= subs.label "Name" %>
            <%= subs.text_field :name, id: "text1" %>
   
            <%= subs.label "Email" %>
            <%= subs.text_field :email, id: "text2" %>
       
            <%= subs.submit 'Subscribe', class: "btn btn-sm btn-default buttons-width" %>
        <% end %>   
    </div>
</div>
<script type="text/javascript">
/*global $*/
//$(".gravatar").mouseenter(function() {
//    console.log("ENTERED");
    //$(this).animate({'border': '10px solid white'}, "slow");
//});
//$(".gravatar").mouseleave(function() {
//    console.log("LEFT");
    //$(this).css("border", "none").fadeOut("slow");
//});
</script>

<!--</div>-->