config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get "resume"     => 'resume#show'
  get "backend"    => 'static_pages#backend'
  get 'learn_html' => 'learn#html'
  get 'learn_css'  => 'learn#css'
  get 'learn_javascript' => 'learn#javascript'
  get 'learn_rails' => 'learn#rails'
  get 'userpanel'  =>  'users#panel'
  get 'about'      =>  'static_pages#about'
  get 'contact'    =>  'static_pages#contact'
  
  
  get "signup"     => 'users#new'
  get "login"      => 'sessions#new'
  get "adminpanel" => 'articles#new'
  
  
  post "adminpanel" => 'articles#new_link'
  post "login"      => 'sessions#create'
  post "/"          => 'static_pages#create'
  post 'contact'=> 'static_pages#new_contact'
  resources :articles, :except => [:new] do
    member do 
      post 'like'
      post 'comment'
    end
  end
  resources :users
  resources :quotes
  resources :forums
  resources :videos, :except => [:new] do
    member do
      post 'like'
      post 'comment'
    end
  end  
  
  
  
  delete 'logout' => 'sessions#destroy'
  delete 'videos/:id' => 'videos#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :likes
    has_many :comments
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
    def thumbs_up_total
        self.likes.where(likes: true).size
    end
    
    def thumbs_down_total
        self.likes.where(likes: false).size
    end
    
    def comments_total
        self.comments.where(article_id: self.id).size
    end
    
    def comment_article
    end
    
    private
        def picture_size
            if picture.size > 5.megabytes
               errors.add(:picture, "should be less than 5 megabytes")
            end
        end
end

app/controllers/articles_controller.rb
# Articles controller should be separated in to different controllers, one
# controller per Model
class ArticlesController < ApplicationController
  before_action :admin_user, only: [:destroy, :edit, :create, :new, :new_link]

  def show
    @article = Article.find(params[:id])
    @videos = Video.all
    @comments = Comment.joins(:article).where({article_id: @article.id})
  end

  def new
    @article = Article.new
  end

  # addd admin panel content
  def new_link
    admin_redirect_link = '/adminpanel'
    @video = Video.new(video_params) unless params[:video].nil?
    @quote = Qoute.new(quote_params) unless params[:quote].nil?
    @userpanel_content = Userpanel.new(userpanel_params) unless params[:userpanel].nil?
    if @video && @video.save
      flash[:success] = 'Youtube Video Link Added!'
      redirect_to admin_redirect_link
    elsif @quote && @quote.save
      flash[:success] = 'New Daily Quote Added!'
      redirect_to admin_redirect_link
    elsif @userpanel_content && @userpanel_content.save
      flash[:success] = 'UserPanel content added!'
      redirect_to admin_redirect_link
    else
      redirect_to admin_redirect_link
    end
  end

  def index
    @articles = Article.all.sort_by{| likes | likes.thumbs_up_total}.reverse
  end

  # create new article action
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = 'Article Saved!'
      redirect_to @article
    else
      ender 'new'
    end
  end

  # edit article action
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Article deleted successfully"
    redirect_to articles_url
  end

  def edit_quote; end

  # Like an article
  def like
    @article = Article.find(params[:id])
    if logged_in?
      like = Like.create(likes: params[:like], user: current_user, article: @article)
      if like.valid?
        redirect_to :back
      else
        flash[:danger] = 'You can not select more than once'
        redirect_to :back
      end
    else
      flash[:warning] = 'Please Login'
      redirect_to :back
    end
  end

  def comment
    @article = Article.find(params[:id])
    if logged_in?
      @comment = Comment.create(comment_params)
      if @comment.save
        flash[:success] = "Comment Added"
        redirect_to :back
      else
        redirect_to :back
      end
    else
      flash[:danger] = "You must login in order to comment"
      redirect_to :back
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :liked, :author_name,
                                    :image_link, :picture)
  end

  def userpanel_params
    params.require(:userpanel).permit(:user_id, :user_video, :html_video,
                                      :css_video, :js_video, :ror_video,
                                      :other_video, :exercise, :html_exercise,
                                      :css_exercise, :js_exercise, :ror_exercise, 
                                      :other_exercise, :project, :final_project,
                                      :course, :html_course, :css_course,
                                      :js_course, :ror_course, :other_course,
                                      :complete, :free, :location)
  end

  def video_params
    params.require(:video).permit(:link)
  end

  def quote_params
    params.require(:quote).permit(:quote, :author)
  end

  def admin_user
    redirect_to(root_url) && flash[:danger] = 'forbidden' unless current_user && current_user.admin?
  end

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :article_id, :video_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    
    def custom_each(array)
        for i in 0...array.length
            i += 1 
            return array[i]
        end
    end
    
    def user_hash(user_id)
        @comments_user = User.all.index_by(&:id)
        @comments_user.each do |key , value|
            if key == user_id
               return value.name
            end
        end
    end
    
end

app/views/articles/edit.html.erb
<div class="container">
    <div class="row">
        <div class="well col-xs col-sm-5 col-md nopadding">
            <%= form_for(@article, html: { multipart: true }) do |x| %>
            
                <h4><%= x.label "Article Title", style: "color:black" %></h4>
                <p><%= x.text_field :title, size: "20x5", style: "color:black" %></p>
                
                <h4><%= x.label "Author Name", style: "color:black" %></h4>
                <p><%= x.text_field :author_name, size: "20x5", style: "color:black" %></p>
                
                <h4><%= x.label "Article", style: "color:black" %></h4>
                <p><%= x.text_area :text, size: "57x20", style: "color:black" %></p>
                
                <span class="picture">
                     <%= x.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
                </span>
                
                <%= x.submit 'Save Changes', class: "btn btn-md btn-primary" %>
                
            <% end %>
        </div>
        <div class="well col-xs col-sm-5 col-md nopadding">
            <%= form_for :video do |x| %>
            
                <h4><%= x.label "Add video Link", style: "color:black" %></h4>
                <p><%= x.text_field :link, size: "20x5", style: "color:black" %></p>
                
                <%= x.submit 'Add Video', class: "btn btn-sm btn-primary" %>
            
            <% end %>
        </div>
    </div>    
</div>

<script type="text/javascript">
    $('#article_picture').bind('change', function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script>

app/views/articles/index.html.erb
<%= provide(:title, 'Articles') %>
<div class="container">
    <div class="row center">
        <h1>Articles</h1>
        <% @articles.each do |x| %>
            <div class="col-md-4 col-sm-6">
                <div class="image">
                    <% if x.picture? %>
                        <%= link_to image_tag(x.picture.url),
                                 article_path(x.id) %>
                    <% else %>
                        <%= link_to image_tag("image.png"),
                        article_path(x.id) %>
                    <% end %>    
                     <!--<p id="article_p">  
                        <%= x.text %>
                    </p>-->
                  
                    <div class="article-title center">
                        <h4><%= link_to x.title, article_path(x.id) %></h4>
                        <p><%= "Author: #{x.author_name}" %></hp>
                        <br>
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        <%= x.thumbs_up_total %>  &nbsp
                        <i class="fa fa-comments" aria-hidden="true"></i>
                        <%= x.comments_total %>
                    </div>
                    <% if logged_in? && current_user.admin? %>
                        <%= link_to "Delete", x, method: :delete, data: { confirm: "Are You Sure?" },
                            class: "btn btn-sm btn-danger" %>
                    <% end %>
                </div>    
            </div>    
        <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<% if logged_in? && current_user.admin?%>
<h3>Admin Panel</h3>
<div class="container-fluid" id="admin-panel">
    <div class="row inline-block-row">
        <div class="col-sm-6 well">
            <%= form_for(@article, html: { multipart: true }) do |x| %>
                <h4><%= x.label "Article Title", class: "black" %></h4>
                <p><%= x.text_field :title, size: "20x5", class: "black" %></p>
                
                <h4><%= x.label "Author Name", class: "black" %></h4>
                <p><%= x.text_field :author_name, size: "20x5", class: "black" %></p>
                
                <h4><%= x.label "Article", class: "black" %></h4>
                <p><%= x.text_area :text, size: "57x20", class: "black" %></p>
                
                <h4><%= x.label "Choose article image", class: "black" %></h4>
                <span class="picture">
                     <%= x.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
                </span>
                
                <%= x.submit 'Upload Article', class: "btn btn-md btn-primary" %>
            <% end %>
        </div>
        <div class="col-sm-6 well">
            <%= form_for :video do |x| %>
            
                <h4><%= x.label "Add video Link",         class: "black" %></h4>
                <p><%=  x.text_field :link, size: "20x5", class: "black" %></p>
                
                <%= x.submit 'Add Video', class: "btn btn-sm btn-primary" %>
            
            <% end %>
        </div>
        <div class="col-sm-6 well">
            <%= form_for :quote do |x| %>
            
                <h4><%= x.label "Add New Daily Quote",      class: "black" %></h4>
                <h4><%= x.label "Author",                   class: "black" %></h4>
                <p><%=  x.text_field :author, size: "20x5", class: "black" %></p>
                
                <h4><%= x.label "Daily Quote Text",        class: "black" %></h4>
                <p><%=  x.text_area  :quote, size: "40x6", class: "black" %></p>
                
                <%= x.submit 'Add New Daily Quote', class: "btn btn-sm btn-primary" %>
                   
            <% end %>
        </div>
        <div class="col-sm-6 well">
            <%= form_for :userpanel do |x| %>
            
                <h3><%= x.label "Add UserPanel Content (Add one at a time - 
                Video/Exercise/Course",        class: "black" %></h3>
                <hr>
                <h4><%= x.label "Video Link",                   class: "black" %></h4>
                <p><%=  x.text_field :user_video, size: "20x5", class: "black" %></p>
                <%= x.label "HTML Video",  class: "black" %>
                <%= x.check_box :html_video  %>
                <%= x.label "CSS Video",   class: "black" %>
                <%= x.check_box :css_video   %>
                <%= x.label "JS Video",    class: "black" %>
                <%= x.check_box :js_video    %>
                <%= x.label "ROR Video",   class: "black" %>
                <%= x.check_box :ror_video   %>
                <%= x.label "OTHER Video", class: "black" %>
                <%= x.check_box :other_video %>
                <hr>
                <h4><%= x.label "Exercise",                  class: "black" %></h4>
                <p><%=  x.text_area :exercise, size: "20x5", class: "black" %></p>
                <%= x.label "HTML exercise",  class: "black" %>
                <%= x.check_box :html_exercise  %>
                <%= x.label "CSS exercise",   class: "black" %>
                <%= x.check_box :css_exercise   %>
                <%= x.label "JS exercise",    class: "black" %>
                <%= x.check_box :js_exercise    %>
                <%= x.label "ROR exercise",   class: "black" %>
                <%= x.check_box :ror_exercise   %>
                <%= x.label "OTHER exercise", class: "black" %>
                <%= x.check_box :other_exercise %>
                <hr>
                <h4><%= x.label "Project",                  class: "black" %></h4>
                <p><%=  x.text_area :project, size: "20x5", class: "black" %></p>
                <hr>
                <h4><%= x.label "Final Project",                  class: "black" %></h4>
                <p><%=  x.text_area :final_project, size: "20x5", class: "black" %></p>
                <hr>
                <h4><%= x.label "Course Link",               class: "black" %></h4>
                <p><%=  x.text_field  :course, size: "20x5", class: "black" %></p>
                <%= x.label "HTML course",  class: "black" %>
                <%= x.check_box :html_course  %>
                <%= x.label "CSS course",   class: "black" %>
                <%= x.check_box :css_course   %>
                <%= x.label "JS course",    class: "black" %>
                <%= x.check_box :js_course    %>
                <%= x.label "ROR course",   class: "black" %>
                <%= x.check_box :ror_course   %>
                <%= x.label "OTHER course", class: "black" %>
                <%= x.check_box :other_course %>
                <%= x.label "Free Course Or Paid (if checked is free)", class: "black" %>
                <%= x.check_box :free %>
                
                <%= x.submit 'Add UserPanel Content', class: "btn btn-sm btn-primary" %>
                   
            <% end %>
        </div>
    </div>    
</div>
<% end %>
<script type="text/javascript">
    $('#article_picture').bind('change', function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script>

app/views/articles/show.html.erb
<% provide(:title, 'Article') %>
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-xs-12">
            <div id="article_p">
                <h3 class="article-title2"><%= @article.title %></h3>
                <h6 class="black">By: <%= @article.author_name %> /
                <%= (@article.created_at.to_s.split(" "))[0] %></h6>
                <hr>            
                <%= @article.text %>
                <div class="row">
                    <div class="col-sm-6">
                        <%= image_tag(@article.picture.url, size: "400x300", 
                        class: "thumbnail") if @article.picture? %>
                    </div>
                    <div class="col-sm-6 center footer-top-border">
                        <br>
                        <h4 class="black">Like</h4>
                        <%= link_to like_article_path(@article, like: true), method: :post do %>
                            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> 
                            &nbsp <%= @article.thumbs_up_total %>
                        <% end %> &nbsp
                        <%= link_to like_article_path(@article, like: false), method: :post do %>
                            <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
                            &nbsp <%= @article.thumbs_down_total %>
                        <% end %>
                    </div>
                </div>
                <div>
                    <h5 class="black">Comments</h5>
                    <hr>
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    <%= form_for :comment, url: {controller: "articles", action: "comment"} do | comment | %>
                        <%= comment.text_area :comment, size: "20x5" %>
                        <%= comment.hidden_field :article_id, :value => @article.id %>
                        <%= comment.hidden_field :user_id, :value => current_user.id unless current_user.nil? %>
                        <%= comment.submit "Comment", class: "btn btn-md btn-default" %>
                    <% end %>
                    <i class="fa fa-comment-o" aria-hidden="true"></i>
                    <%= @article.comments_total %>
                    <br>
                    <% @comments.each do |x| %>
                        <div class="well">
                            <%= gravatar_for_comments User.find(x.user_id) if !x.user_id.nil? %>
                            <h6 class="black"><%= user_hash(x.user_id) %></h6>
                            <p class="black small-font"><%= x.comment %></p>
                        </div>
                        <hr>
                    <% end %>
                </div>
            </div>
            <% if logged_in? && current_user.admin? %>
                <%= link_to "Edit", edit_article_path, class: "btn btn-sm btn-primary" %>
            <% end %>
            <h5 class="black">Comments</h5>
        </div>
        <div class="col-sm-3 col-xs-10 center">
            <h4>Latest Videos</h4>
            <% @videos.find_each do |x| %>
                <div>
                    <frame scrolling="auto">
                    <iframe width="300" height="200" id="video"
                            src=<%= "https://www.youtube.com/embed/#{x.link}" %> 
                            frameborder="0" allowfullscreen>
                    </iframe>
                    </frame>
                </div>
            <% end %>    
        </div>
    </div>
</div>