config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get "resume"     => 'resume#show'
  get "backend"    => 'static_pages#backend'
  get 'learn_html' => 'learn#html'
  get 'learn_css'  => 'learn#css'
  get 'learn_javascript' => 'learn#javascript'
  get 'learn_rails' => 'learn#rails'
  get 'userpanel'  =>  'users#panel'
  get 'about'      =>  'static_pages#about'
  get 'contact'    =>  'static_pages#contact'
  
  
  get "signup"     => 'users#new'
  get "login"      => 'sessions#new'
  get "adminpanel" => 'articles#new'
  
  
  post "adminpanel" => 'articles#new_link'
  post "login"      => 'sessions#create'
  post "/"          => 'static_pages#create'
  post 'contact'=> 'static_pages#new_contact'
  resources :articles, :except => [:new] do
    member do 
      post 'like'
      post 'comment'
    end
  end
  resources :users
  resources :quotes
  resources :forums
  resources :videos, :except => [:new] do
    member do
      post 'like'
      post 'comment'
    end
  end  
  
  
  
  delete 'logout' => 'sessions#destroy'
  delete 'videos/:id' => 'videos#destroy'

end

app/models/video.rb
class Video < ActiveRecord::Base
    has_many :likes
    has_many :comments
    
    def thumbs_up_total
        self.likes.where(likes: true).size
    end
    
    def thumbs_down_total
        self.likes.where(likes: false).size
    end
    
    def comments_total
        self.comments.where(video_id: self.id).size
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    before_action :admin_user, only: [:destroy]
    
    def show
        @video = Video.find(params[:id])
        @articles = Article.all
        @comments = Comment.joins(:video).where({video_id: @video.id})
    end
    
    def index 
       @videos = Video.paginate(page: params[:page], per_page: 9)
    end
    
    def destroy
       Video.find(params[:id]).destroy
       flash[:success] = "Video Deleted Successfully"
       redirect_to videos_url
    end
    
    def like
        @video = Video.find(params[:id])
        if logged_in?
            like = Like.create(likes: params[:like], user: current_user, video: @video)
            if like.valid?
                redirect_to :back
            else
                flash[:danger] = "You can not select more than once"
                redirect_to :back
            end
        else
            flash[:warning] = "Please Login"
            redirect_to :back
        end
    end
    
    def comment
        @video = Video.find(params[:id])
        if logged_in?
            @comment = Comment.create(comment_params)
            if @comment.save
                flash[:success] = "Comment Added" 
                redirect_to :back
            else
                redirect_to :back
            end 
        else
            flash[:danger] = "You must login in order to comment"
            redirect_to :back
        end
    end
    
    private
    
    def admin_user
       redirect_to(root_url) unless current_user.admin? 
    end
    
    def comment_params
        params.require(:comment).permit(:comment, :user_id, :article_id, :video_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<div class="container"> 
    <div class="row">
        <h1>videos</h1>
        <%= @videos.find_each do |x| %>
            <div class="col-sm-6 col-md-4">
                <div id="video" class="center">
                    <% puts "#{x.link}" %>
                    <iframe width="380" height="300" id="video"
                        src=<%= "https://www.youtube.com/embed/#{x.link}" %> frameborder="0" allowfullscreen>
                    </iframe>
                    <h4><%= link_to x.title, video_path(x.id) %></h4>
                    <div style="color: white">
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        &nbsp <%= x.thumbs_up_total %> &nbsp
                        <i class="fa fa-comment-o" aria-hidden="true"></i>
                        &nbsp <%= x.comments_total %>
                    </div>
                </div>
                <% if logged_in? && current_user.admin? %>
                    <%= link_to "Delete", { :controller => :videos, :action => 'destroy', :id => x.id } , method: :delete, 
                        data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
                <% end %>    
            </div>
        <% end %> 
    </div>
</div>

app/views/videos/show.html.erb
<% provide(:title, 'Video') %>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div id="video2">
                <iframe src=<%= "https://www.youtube.com/embed/#{@video.link}" %>
                                    frameborder="0" allowfullscreen class="show-video">
                </iframe>
                <div class="row">
                    <span class="white">Like</span>&nbsp
                    <%= link_to like_video_path(@video, like: true), method: :post do %>
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> 
                        &nbsp <%= @video.thumbs_up_total %>
                    <% end %> &nbsp
                    <%= link_to like_video_path(@video, like: false), method: :post do %>
                        <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
                        &nbsp <%= @video.thumbs_down_total %>
                    <% end %>
                </div>
            </div>
            <h3 class="article-title2"><%= @video.title unless @video.nil? %></h3>
        </div>
        <!--<% if logged_in? && current_user.admin? %>
            <%= link_to "Edit", edit_video_path, class: "btn btn-sm btn-primary" %>
            <% end %>-->
        <div class="row">
            <div id="video-comments">
                <h5>Comments</h5>
                <hr>
                <i class="fa fa-comments white" aria-hidden="true"></i>
                <%= form_for :comment, url: {controller: "videos", action: "comment"} do | comment | %>
                    <%= comment.text_area :comment, size: "20x5" %>
                    <%= comment.hidden_field :video_id, :value => @video.id %>
                    <%= comment.hidden_field :user_id, :value => current_user.id unless current_user.nil? %>
                    <%= comment.submit "Comment", class: "btn btn-md btn-default" %>
                <% end %>
                <i class="fa fa-comment-o white" aria-hidden="true"></i>
                <span class="white"><%= @video.comments_total %></span>
                <br>
                <% @comments.each do |x| %>
                    <div class="well">
                        <%= gravatar_for_comments User.find(x.user_id) if !x.user_id.nil? %>
                            <h6 class="black"><%= user_hash(x.user_id) %></h6>
                            <p class="black small-font"><%= x.comment %></p>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>