config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get "resume"     => 'resume#show'
  get "backend"    => 'static_pages#backend'
  get 'learn_html' => 'learn#html'
  get 'learn_css'  => 'learn#css'
  get 'learn_javascript' => 'learn#javascript'
  get 'learn_rails' => 'learn#rails'
  get 'userpanel'  =>  'users#panel'
  get 'about'      =>  'static_pages#about'
  get 'contact'    =>  'static_pages#contact'
  
  
  get "signup"     => 'users#new'
  get "login"      => 'sessions#new'
  get "adminpanel" => 'articles#new'
  
  
  post "adminpanel" => 'articles#new_link'
  post "login"      => 'sessions#create'
  post "/"          => 'static_pages#create'
  post 'contact'=> 'static_pages#new_contact'
  resources :articles, :except => [:new] do
    member do 
      post 'like'
      post 'comment'
    end
  end
  resources :users
  resources :quotes
  resources :forums
  resources :videos, :except => [:new] do
    member do
      post 'like'
      post 'comment'
    end
  end  
  
  
  
  delete 'logout' => 'sessions#destroy'
  delete 'videos/:id' => 'videos#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :likes
    has_many :comments
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
    def thumbs_up_total
        self.likes.where(likes: true).size
    end
    
    def thumbs_down_total
        self.likes.where(likes: false).size
    end
    
    def comments_total
        self.comments.where(article_id: self.id).size
    end
    
    def comment_article
    end
    
    private
        def picture_size
            if picture.size > 5.megabytes
               errors.add(:picture, "should be less than 5 megabytes")
            end
        end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :video
    belongs_to :article
    belongs_to :user
    
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
end

app/models/forum.rb
class Forum < ActiveRecord::Base
    
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :video
    belongs_to :article
    belongs_to :user
    
    validates_uniqueness_of :user, scope: [:article, :video]
end

app/models/qoute.rb
class Qoute < ActiveRecord::Base
            
    def self.process_quote(q)
        current_date_array = ((Time.now).to_s.split("-"))[2].split(" ")
        counter = 1
        q.each do |x|
            if current_date_array[0][0,1] == '0'
                current_date_array[0] = current_date_array[0][1,1]
            end
            if counter.to_s == current_date_array[0]
                return x
            end 
            counter += 1
        end
    end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :likes
    has_many :comments
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name,presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    #validates :role, presence: true, length: {maximum: 6 }
    
    has_secure_password
    validates :password, length: { minimum: 6 }, allow_blank: true
    
    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/models/userpanel.rb
class Userpanel < ActiveRecord::Base
    belongs_to :user
end

app/models/video.rb
class Video < ActiveRecord::Base
    has_many :likes
    has_many :comments
    
    def thumbs_up_total
        self.likes.where(likes: true).size
    end
    
    def thumbs_down_total
        self.likes.where(likes: false).size
    end
    
    def comments_total
        self.comments.where(video_id: self.id).size
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Return title on a per page basis 
    def full_title(page_title = '')
        base_title = "RailsBit"
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    
    def custom_each(array)
        for i in 0...array.length
            i += 1 
            return array[i]
        end
    end
    
    def user_hash(user_id)
        @comments_user = User.all.index_by(&:id)
        @comments_user.each do |key , value|
            if key == user_id
               return value.name
            end
        end
    end
    
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    # Remembers a user in a persistent session.
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
    def current_user?(user)
        user == current_user
    end
    
    # Returns the current logged-in user (if any).
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end
    
    # Forgets a persistent session.
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    # Logs out the current user.
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || '/userpanel')
        session.delete(:forwarding_url)
    end
        # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def amounts
       ["$2", "$5", "$10", "$15", "$20", "$30", "$50"] 
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name)
    end
    
    def gravatar_for_comments(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, class: "grav_size", alt: user.name)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_footer.html.erb
        <div class="center top_padding">
            <a id="footer-logo">RailsBit.<span class="small">com</span></a>
        </div>
<div class="footer-top-border">        
    <div class="container">        
        <div class="row center">
            <div class="col-sm-3">
                <%= image_tag('CLOUD.jpg', id: "footer-image") %>    
            </div>
            <div class="col-sm-3">
                    <ul class="footer-style">
                        <li><a>Sitemap</a></li>
                        <li><a>Privacy Policy</a></li>
                        <li><a>Terms of Use</a></li>
                        <li><a>Location</a></li>
                        <li><a>Navigation</a></li>
                    </ul>
            </div>
            <div class="col-sm-3">
                    <ul class="footer-style">
                        <li><a>Signup</a></li>
                        <li><a>Login</a></li>
                        <li><a>Latest Articles</a></li>
                        <li><a>Learn</a></li>
                        <li><a>Magazine</a></li>
                    </ul>
            </div>
            <div class="col-sm-3">
                    <ul class="footer-style">
                        <li><a>Testimonials</a></li>
                        <li><a>About</a></li>
                        <li><a>Videos</a></li>
                        <li><a>Articles</a></li>
                        <li><a>Channels</a></li>
                    </ul>
            </div>
        </div>
    </div> 
</div>    
<footer class="center">
            <h4>&copyRailsBit 2017</h4>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="page_navbar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" 
                    data-target="#navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <a class="navbar-brand"><%= link_to 'RailsBit.', root_path, id: "logo" %></a>
        </div> 
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <!--<li class="dropdown">
                    <a href='#' class="dropdown-toggle links" data-toggle="dropdown">
                        Articles
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "HTML", learn_html_path, class: 'links-sub' %></li>
                        <li><%= link_to "CSS",  learn_css_path, class: 'links-sub' %></li>
                        <li><%= link_to "JavaScript", learn_javascript_path, class: 'links-sub' %></li>
                        <li><%= link_to "Ruby on Rails", learn_rails_path, class: 'links-sub' %></li>
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a href='#' class="dropdown-toggle links" data-toggle="dropdown">
                        Videos
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Articles", articles_path, class: 'links-sub' %></li>
                        <li><%= link_to "Videos",   videos_path,   class: 'links-sub' %></li>
                        <li><%= link_to "Tips",       '#',         class: 'links-sub' %></li>
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a href='#' class="dropdown-toggle links" data-toggle="dropdown">
                        About
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Our Story", '#', class: 'links-sub' %></li>
                        <li><%= link_to "Vlog",     '#',  class: 'links-sub' %></li>
                    </ul>
                </li>-->
                
                <li><%= link_to "Articles", articles_path, class: 'links' %></li>
                <li><%= link_to "Videos",   videos_path,   class: 'links' %></li>
                <li><%= link_to "Forum",    forums_path ,   class: 'links' %></li>
                <li><%= link_to "Contact",  contact_path,  class: 'links' %></li>
            </ul>
            <% if logged_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <% if logged_in? && current_user.admin? %>
                        <li><%= link_to "Admin Panel", adminpanel_path, class: "links" %></li>
                        <li><%= link_to "Users", users_path, class: "links" %></li>
                    <% end %> 
                    <li><%= link_to "UserPanel", userpanel_path, class: "links" %></li>
                    <li class="dropdown">
                        <a href='#' class="dropdown-toggle links" 
                           data-toggle="dropdown">
                            Account
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile",  current_user,   class: 'links-sub' %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user), class: 'links-sub' %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: "delete", class: 'links-sub' %>
                            </li>
                        </ul>
                    </li>
                </ul>
            <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li id="links"><%= link_to "Login",   login_path,  class: 'links' %></li>
                    <li id="links"><%= link_to "Sign Up", signup_path, class: 'links' %></li>
                    <i class="icon icon-search"></i>
                </ul>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700,800" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= render 'layouts/navbar' %>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
  <!--<%= debug(params) if Rails.env.development? %>-->
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<script>
    $(function() {
  setTimeout(function(){
    $('.alert').slideUp(250);
      }, 4000);
    });
</script>